blog/urls.py
from django.urls import path
from blog import views


app_name = 'post'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.search, name='search'),
    path('about/', views.AboutView.as_view(), name='about'),

    # crud
    path('explore/', views.PostListView.as_view(), name='list'),
    path('article/<slug:slug>', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('article/<slug:slug>/update/',
         views.PostUpdateView.as_view(), name='update'),
    path('article/<slug:slug>/delete/',
         views.PostDeleteView.as_view(), name='delete'),
    # publish
    path('article/<slug:slug>/publish/', views.publish, name='publish'),
    path('article/<slug:slug>/unpublish/', views.unpublish, name='unpublish'),
    path('publish/', views.publish_now, name='publish_now'),
    # categories
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
    path('category/<slug:slug>/<slug:sub_slug>',
         views.SubCategoryListView.as_view(), name='sub_category'),
    path('ajax/load_subcategories/', views.load_subcategories,
         name='ajax_load_subcategories'),
]

cricket_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('marketing', include('marketing.urls')),
    path('accounts/', include('users.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('ckeditor/', include(
         'ckeditor_uploader.urls')),
]

# inorder to display images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from PIL import Image

from category.models import Category
from ckeditor_uploader.fields import RichTextUploadingField
from subcategory.models import SubCategory


class Post(models.Model):
    """Model definition for Post."""

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    main_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200)
    news_pic = models.ImageField(upload_to='news_pics')
    video_link = models.CharField(max_length=200, blank=True, null=True)
    short_description = models.TextField()
    long_description = RichTextUploadingField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey(
        Category, verbose_name="Category", on_delete=models.CASCADE)

    sub_category = models.ForeignKey(
        SubCategory, verbose_name="sub_category", on_delete=models.CASCADE, blank=True, null=True)

    featured = models.BooleanField(default=False)
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        """Unicode representation of Post."""
        return self.main_title

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('post:update',  kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('post:delete',  kwargs={'slug': self.slug})

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    def get_category_list_url(self):
        return reverse('post:category', kwargs={
            'slug': self.category.slug,

        })

    def subcat(self):
        if self.sub_category:
            return self.sub_category.sub_slug

    def get_sub_category_list_url(self):
        return reverse('post:sub_category', kwargs={
            'slug': self.category.slug,
            'sub_slug': self.subcat(),


        })

    def get_user_post(self):
        return reverse('user-posts', kwargs={
            'username': self.author.username
        })

    class Meta:
        ordering = ["-published_date"]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.news_pic.path)

        if img.height > 800 or img.width > 800:
            output_size = (800, 800)
            img.thumbnail(output_size)
            img.save(self.news_pic.path)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def get_commented_user_post(self):
        return reverse('user-posts', kwargs={
            'username': self.user.username
        })

category/models.py
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="Title")
    slug = models.SlugField(max_length=100, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['created_at']

    def __str__(self):
        return self.title

    def get_latest(self):
        return self.post_set.filter(featured=True).order_by('-published_date')[:3]

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)


def slug_post_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(instance.title, allow_unicode=True)
        instance.slug = slug
        instance.save()


post_save.connect(slug_post_save_receiver, sender=Category)

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView, View)
from django.views.generic.list import MultipleObjectMixin

from blog.forms import CommentForm, PostForm, SearchForm
from blog.models import Comment, Post
from category.models import Category
from marketing.forms import EmailSignupForm
from marketing.models import Signup
from subcategory.models import SubCategory


class AboutView(TemplateView):
    template_name = "blog/about.html"


class HomeView(View):
    def get(self, *args, **kwargs):
        post_list = Post.objects.filter(
            featured=True, published_date__lte=timezone.now()).order_by('-published_date')[:3]
        latest = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('-published_date')[:6]
        pics = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('-published_date')[3:7]
        form = EmailSignupForm()
        context = {
            'post_list': post_list,
            'latest': latest,
            'pics': pics,
            'form': form,
        }
        return render(self.request, template_name='blog/home.html', context=context)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Successfully subscribed")
        return redirect("home")


# class CategoryListView(ListView):
#     model = Post
#     context_object_name = 'post_list'
#     paginate_by = 5

    # def get_queryset(self):
    #     cate = get_object_or_404(Category, title=self.kwargs.get('title'))
    #     return cate.post_set.filter(published_date__lte=timezone.now()).order_by('-published_date')


# class SubCategoryListView(ListView):
#     model = Post
#     context_object_name = 'post_list'
#     paginate_by = 5

#     def get_queryset(self):
#         sub_cate = get_object_or_404(
#             SubCategory, sub_title=self.kwargs.get('sub_title'))
#         return Post.objects.filter(sub_category=sub_cate, published_date__lte=timezone.now()).order_by('-published_date')


class PostListView(ListView):
    model = Post
    paginate_by = 3
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now())


class DraftListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/post_draft.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        context['post_list'] = Post.objects.filter(
            published_date__isnull=True, author=user).order_by('-create_date')

        return context


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        user_posts = Post.objects.filter(
            author=user, published_date__lte=timezone.now())
        p = Paginator(user_posts, 6)
        page = self.request.GET.get('page', 1)

        try:
            context['page_obj'] = p.page(page)
        except EmptyPage:
            context['page_obj'] = p.page(p.num_pages)
        context['author'] = user
        context['is_paginated'] = True
        return context


class CategoryListView(ListView):
    model = Post
    context_object_data = 'post_list'
    paginate_by = 4
    template_name = 'blog/blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        context['category_meta'] = cate
        context['category_list'] = Category.objects.all()
        context['most_recent'] = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('published_date')[:3]
        return context

    def get_queryset(self):
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return cate.post_set.filter(published_date__lte=timezone.now()).order_by('-published_date')


class SubCategoryListView(ListView):
    model = Post
    context_object_data = 'post_list'
    paginate_by = 4
    template_name = 'blog/blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cate = get_object_or_404(
            SubCategory, sub_slug=self.kwargs.get('sub_slug'))
        context['sub_category_meta'] = cate
        context['category_list'] = Category.objects.all()
        context['most_recent'] = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('published_date')[:3]
        return context

    def get_queryset(self):
        cate = get_object_or_404(
            SubCategory, sub_slug=self.kwargs.get('sub_slug'))
        return cate.post_set.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post
    form = CommentForm()
    template_name = "blog/post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']
        cate = post.category
        context['category_list'] = Category.objects.all()
        context['form'] = self.form
        context['most_recent'] = cate.post_set.filter(
            published_date__lte=timezone.now()).order_by('-published_date')[:3]
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post:detail", kwargs={
                'slug': post.slug
            }))


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    form_class = PostForm

    def test_func(self):
        return self.request.user.is_staff

    def get_initial(self):
        return {
            "author": self.request.user
        }


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author and self.request.user.is_staff:
            return True
        return False

    def get_initial(self):
        return {
            "author": self.request.user
        }


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post:list')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author and self.request.user.is_staff:
            return True
        return False


@login_required
def publish(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user == post.author and request.user.is_staff:
        post.publish()
        return redirect('post:detail', slug=slug)
    else:
        return redirect('post:list')


@login_required
def unpublish(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user == post.author and request.user.is_staff:
        post.published_date = None
        post.save()
    return redirect('post:detail', slug=slug)


@login_required
def publish_now(request):
    # creating a form using request
    post = PostForm(request.POST, request.FILES)

    if post.is_valid():
        post_save = post.save(commit=False)
        # setting the published date
        post_save.publish()
        return redirect('post:detail', slug=post_save.slug)
    return redirect("post:list")


def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = SubCategory.objects.filter(
        category_id=category_id).order_by('sub_title')
    return render(request, template_name='blog/subcategory_drop_down_list.html', context={'subcategories': subcategories})


def search(request):

    if request.method == 'POST':
        print(request.POST.get('q'))
        form = SearchForm(request.POST)
        if form.is_valid():

            queryset = Post.objects.all()
            query = form.cleaned_data.get('q')
            if query:
                queryset = queryset.filter(
                    Q(main_title__icontains=query) |
                    Q(short_description__icontains=query)
                ).distinct()

            context = {
                'queryset': queryset,
            }
            return render(request, template_name='blog/search_results.html', context=context)
    return render(request, template_name='blog/search_results.html')

blog/templates/blog/about.html
{% extends 'base.html' %}


{% block body_block %}
   <div class="row">
        <div class="col-6 mx-auto mt-5 pt-5">
            Coming Soon!
        </div>
   </div>
{% endblock body_block %}
    

blog/templates/blog/aside.html
<aside class="col-lg-4">
    <!-- Widget [Search Bar Widget]-->
    <div class="widget search">
        <header>
            <h3 class="h6">Search the blog</h3>
        </header>
        <form action="{% url 'post:search' %}" class="search-form" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
            </div>
        </form>
    </div>
    <!-- Widget [Latest Posts Widget]        -->
    <div class="widget latest-posts">
        <header>
            <h3 class="h6">Latest Posts</h3>
        </header>
        <div class="blog-posts">


            {% for postdetail in most_recent %}
            {% if post.pk == postdetail.pk %}
            {% else %}
            <div class="card mb-3 side_list">
                <a href="{{ postdetail.get_absolute_url }}">

                    {% if postdetail.news_pic %}
                    <img class="card-img-top side_image" src="{{ postdetail.news_pic.url }}" alt="Card image cap" />
                    {% else %}
                    <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{postdetail.video_link}}"
                        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
                    {% endif %}

                </a>

                <div class="card-body">
                    <a href="{{ postdetail.get_absolute_url }}">
                        <h5 class="card-title text-dark text-decoration-none ">
                            {{ postdetail.main_title }}
                        </h5>
                    </a>
                    <p class="card-text">
                        <small class="text-muted">{{ postdetail.published_date }}</small>
                    </p>
                </div>
            </div>
            {% endif %} {% endfor %}


        </div>
    </div>
    <!-- Widget [Categories Widget]-->
    <div class="widget categories">
        <header>
            <h3 class="h6">Categories</h3>
        </header>

        {% for cat in category_list %}
        <div class="item d-flex justify-content-between"><a href="#">{{cat.title}}
            </a><span>{{cat.post_set.count}}</span></div>
        {% endfor %}



    </div>

</aside>

blog/templates/blog/post_draft.html
{% extends 'base.html' %}
{% load static %}

{% block meta_tags %}
<meta name="robots" content="noindex, nofollow">
{% endblock meta_tags %}


{% block title %}
My Draft List
{% endblock title %}


{% block style %}
<link rel="stylesheet" href=" {% static 'blog/css/draft.css' %} ">
{% endblock style %}


{% block body_block %}


{% for post in post_list %}
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-9 content-section">
            <div class="row post-header">
                <div class="col-2 col-md-1">
                    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
                </div>
                <div class="col-8 col-md-10 border-bottom">
                    <div class="row">
                        <div class="col-12">
                            <a href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                        </div>
                        <div class="col-12">
                            <small class="text-muted">{{ post.published_date }}</small>

                        </div>
                    </div>
                </div>
                <div class="col-1 ">

                    {% if user.is_authenticated and post.author == user %}
                    <button class="btn btn-link dropdown-toggle edit-button" type="button" id="gedf-drop1"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-ellipsis"></i>
                    </button>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                        <div class="h6 dropdown-header">Configuration</div>
                        <a class="dropdown-item" href="{{post.get_update_url}}">Edit</a>
                        <a class="dropdown-item" href="{% url 'post:publish' slug=post.slug %}">Publish</a>
                        <a class="dropdown-item" href="{{post.get_delete_url}}">Delete</a>
                    </div>
                    {% endif %}

                </div>
            </div>

            <div class="row">

                {% if post.news_pic  %}
                <div class="col-12 col-md-5 mt-4 mb-3">
                    <img class="img-fluid" src="{{ post.news_pic.url }}" alt="">
                </div>
                <div class="col-12 col-md-7">
                    <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a></h2>
                    <p class="article-content text-justify">{{post.short_description|safe|linebreaksbr}}</p>
                </div>
                {% elif post.video_link %}
                <div class="col-12 col-md-7 mt-4 mb-3">
                    <iframe width="100%" height="300" src="https://www.youtube.com/embed/{{post.video_link}}"
                        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
                </div>
                <div class="col-12 col-md-5">
                    <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a></h2>
                    <p class="article-content text-justify">{{post.short_description|safe|linebreaksbr}}</p>
                </div>
                {% else %}
                <div class="col-12 col-md-12 pl-5 mt-2">
                    <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a></h2>
                    <p class="article-content text-justify">{{post.short_description|safe|linebreaksbr}}</p>
                </div>
                {% endif %}



            </div>

        </div>
        <div class="col-lg-3 list-section d-none d-lg-block ">

        </div>
    </div>
</div>

{% endfor %}
<div class="col-12 col-md-8 d-flex justify-content-center">
    {% if is_paginated %}

    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}
</div>
{% endblock body_block %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta_tags %}
<meta name="robots" content="noindex, nofollow">
{% endblock meta_tags %}


{% block title %}
New Article
{% endblock title %}


{% block style %}
<link rel="stylesheet" href=" {% static 'blog/css/post_form.css' %} ">
{% endblock style %}



{% block body_block %}
<div class="container">
    <div class="row content-section">
        <div class="col-9 mr-auto ml-auto mb-3 mt-3 ">
            <h1>
                {% if not form.instance.pk %}
                Create
                {% else %}
                Update
                {% endif %}
            </h1>
            {{ form.media }}
            <form method="POST" enctype="multipart/form-data" id="postForm"
                data-subcategories-url="{% url 'post:ajax_load_subcategories' %}" novalidate>
                {% csrf_token %}
                {{form|crispy}}


                {% if form.instance.pk %}
                <input class="btn btn-primary " type="submit" value="Save">
                {% else %}
                <input class="btn btn-primary " type="submit" value="Draft">
                <input class="btn btn-primary" formaction="{% url 'post:publish_now' %}" type="submit"
                    value="Publish Now">
                {% endif %}
            </form>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_category").change(function () {
        var url = $("#postForm").attr("data-subcategories-url");  // get the url of the `load_cities` view
        var categoryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'category': categoryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_sub_category").html(data);  // replace the contents of the city input with the data that came                                            
            }
        });

    });
</script>

{% endblock body_block %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block meta_tags %}

<meta name="description"
    content="Financial knowledge is more important than Common sense? We prove the best fianacial tips, guides to boost your networth">
{% endblock meta_tags %}

{% block title %}
අනාගතය - Government Exams, Jobs
{% endblock title %}

{% block style %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'blog/js/infinite.min.js' %}"></script>

{% endblock style %}


{% block body_block %}



<div class="container">
    <div class="row">
        <div class="col-12 col-lg-9  infinite-container">
            <div class="infinite-item">
                {% for post in post_list %}


                <div class="content-section">
                    <div class="row post-header">
                        <div class="col-2 col-md-1">
                            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"
                                alt="{{post.author.username}}">
                        </div>
                        <div class="col-8 col-md-10 border-bottom">
                            <div class="row">
                                <div class="col-12">
                                    <a class="text-decoration-none text-dark"
                                        href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                                </div>
                                <div class="col-12">
                                    <small class="text-muted">{{ post.published_date }}</small>

                                </div>
                            </div>
                        </div>
                        <div class="col-1 ">

                            {% if user.is_authenticated and post.author == user %}
                            <button class="btn btn-link dropdown-toggle edit-button" type="button" id="gedf-drop1"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-ellipsis"></i>
                            </button>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                <div class="h6 dropdown-header">Configuration</div>
                                <a class="dropdown-item" href="{{post.get_update_url}}">Edit</a>
                                <a class="dropdown-item" href="{% url 'post:unpublish' slug=post.slug %}">Move to
                                    Drafts</a>
                                <a class="dropdown-item" href="{{post.get_delete_url}}">Delete</a>
                            </div>
                            {% endif %}

                        </div>
                    </div>

                    <div class="row">

                        {% if post.news_pic  %}
                        <div class="col-12 col-md-5 mt-4 mb-3">
                            <img class="img-fluid" src="{{ post.news_pic.url }}" alt="{{post.main_title}}">
                        </div>
                        <div class="col-12 col-md-7 article-head-title">
                            <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a>
                            </h2>
                            <p class="article-content text-justify">{{post.short_description|truncatechars:200|safe}}
                            </p>
                        </div>
                        {% elif post.video_link %}
                        <div class="col-12 col-md-7 mt-4 mb-3 article-head-title">
                            <iframe width="100%" height="300" src="https://www.youtube.com/embed/{{post.video_link}}"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                        </div>
                        <div class="col-12 col-md-5 article-head-title">
                            <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a>
                            </h2>
                            <p class="article-content text-justify">{{post.short_description|truncatechars:9|safe}}
                            </p>
                        </div>
                        {% else %}
                        <div class="col-12 col-md-12 pl-5 mt-2">
                            <h2><a class="article-title" href="{{ post.get_absolute_url}}">{{ post.main_title }}</a>
                            </h2>
                            <p class="article-content text-justify">{{post.short_description|truncatechars:200|safe}}
                            </p>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 list-section d-none d-lg-block ">

        </div>

    </div>


    <div class="loading" style="display: none;">
        Loading...
    </div>

    {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
    {% endif %}
</div>
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function ($items) {
            $('.loading').hide();
        }
    });
</script>

{% endblock body_block %}