blog/urls.py
from django.urls import path
from blog import views


app_name = 'post'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.search, name='search'),
    path('about/', views.AboutView.as_view(), name='about'),

    # crud
    path('explore/', views.PostListView.as_view(), name='list'),
    path('article/<slug:slug>', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('article/<slug:slug>/update/',
         views.PostUpdateView.as_view(), name='update'),
    path('article/<slug:slug>/delete/',
         views.PostDeleteView.as_view(), name='delete'),
    # publish
    path('article/<slug:slug>/publish/', views.publish, name='publish'),
    path('article/<slug:slug>/unpublish/', views.unpublish, name='unpublish'),
    path('publish/', views.publish_now, name='publish_now'),
    # categories
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
    path('category/<slug:slug>/<slug:sub_slug>',
         views.SubCategoryListView.as_view(), name='sub_category'),
    path('ajax/load_subcategories/', views.load_subcategories,
         name='ajax_load_subcategories'),
]

cricket_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('marketing', include('marketing.urls')),
    path('accounts/', include('users.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('ckeditor/', include(
         'ckeditor_uploader.urls')),
]

# inorder to display images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

subcategory/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify

from category.models import Category


class SubCategory(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    sub_title = models.CharField(max_length=255, verbose_name="Title")
    category = models.ForeignKey(
        Category, verbose_name="Category", on_delete=models.CASCADE)
    sub_slug = models.SlugField(max_length=100, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "SubCategory"
        verbose_name_plural = "SubCategories"
        ordering = ['sub_title']

    def __str__(self):
        return self.category.title + " " + self.sub_title

    # def save(self, *args, **kwargs):
    #     self.sub_slug = slugify(self.sub_title)
    #     super().save(*args, **kwargs)


def slug_post_save_receiver(sender, instance, *args, **kwargs):
    if not instance.sub_slug:
        slug = slugify(instance.sub_title, allow_unicode=True)
        instance.sub_slug = slug
        instance.save()


post_save.connect(slug_post_save_receiver, sender=SubCategory)

templates/_header_links.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css'%}">
<!-- Custom icon font-->
<link rel="stylesheet" href="{% static 'css/fontastic.css'%}">
<!-- Google fonts - Open Sans-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<!-- Fancybox-->
<link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css'%}">
<!-- theme stylesheet-->
<link rel="stylesheet" href="{% static 'css/style.default.css'%}" id="theme-stylesheet">
<!-- Custom stylesheet - for your changes-->
<link rel="stylesheet" href="{% static 'css/custom.css'%}">
<!-- Favicon-->
<link rel="shortcut icon" href="favicon.png">
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153622522-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-153622522-1');
</script>

templates/_header_meta.html
<meta http-equiv="Content-Type" content="text/html; charset=" UTF-8">
<meta name="google-site-verification" content="NSy31Yf8c1oaQTtURmaZPAJU_VGvnhvkETmeGdbQ0uw" />
<!-- Required meta tags -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="robots" content="noindex, nofollow">

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    {% include '_header_meta.html' %}
    {% include '_header_links.html' %}

    {% block meta_tags %}
    {% endblock meta_tags %}

    {% block style %}
    {% endblock style %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon_anaa.ico' %}">
    <title>
      {% block title %}
      {% endblock title %}
    </title>
  </head>

  <body>
    {% include 'navbar.html' %}

    {% block body_block %}
    {% endblock body_block %}

    {% include 'footer.html' %}
    {% include 'scripts.html' %}

  </body>

</html>

templates/footer.html
{% load static %}

<!-- Page Footer-->
<footer class="main-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="logo">
                    <h6 class="text-white">අනාගතය</h6>
                </div>
                <div class="contact-details">
                    <p>අනාගතය</p>
                    <p>Gangodawila, Nugegoda, Sri Lanka</p>
                    <p>Email: <a href=""></a>අනාගතය</p>
                    <ul class="social-menu">
                        <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-5">
                <div class="menus d-flex justify-content-between">
                    <ul class="list-unstyled">
                        <li> <a href="{% url 'post:about' %}">About Us</a></li>
                        <li> <a href="#">Contact Us</a></li>
                        <li> <a href="#">Our Team</a></li>
                        <li> <a href="#">Consultation</a></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li> <a href="#">Disclaimer</a></li>
                        <li> <a href="#">FAQ</a></li>
                        <li> <a href="#">Privacy &amp; Policy </a></li>
                        <li> <a href="#">Terms &amp; Conditions</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <div class="copyrights">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2019-2020. All rights reserved. @anaagathaya.com.</p>
                </div>
                <div class="col-md-6 text-right">
                    <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel"
                            class="text-white">Bootstrapious</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
<header class="header">
    <!-- Main Navbar-->
    <nav class="navbar navbar-expand-lg">
        <div class="search-area">
            <div class="search-area-inner d-flex align-items-center justify-content-center">
                <div class="close-btn"><i class="icon-close"></i></div>
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8">
                        <form action="{% url 'post:search' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="search" name="q" id="search" placeholder="What are you looking for?">
                                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <!-- Navbar Brand -->
            <div class="navbar-header d-flex align-items-center justify-content-between">
                <!-- Navbar Brand --><a href="/" class="navbar-brand">අනාගතය</a>
                <!-- Toggle Button-->
                <button type="button" data-toggle="collapse" data-target="#navbarcollapse"
                    aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler"><span></span><span></span><span></span></button>
            </div>
            <!-- Navbar Menu -->
            <div id="navbarcollapse" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'post:list' %}">Explore </a>
                    </li>
                    {% for category in categories %}
                    {% if category.subcategory_set.all %}
                    <li class="nav-item dropdown mydropdowncss ">
                        <a class="nav-link dropdown-toggle" href="{% url 'post:category' slug=category.slug %}">
                            {{category.title|title}}
                        </a>
                        <div class="dropdown-menu ">
                            {% for sub in category.subcategory_set.all %}
                            <a class="dropdown-item"
                                href="{% url 'post:sub_category' slug=category.slug sub_slug=sub.sub_slug %}">{{ sub.sub_title|title }}</a>
                            {% endfor %}

                        </div>
                    </li>

                    {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'post:category' slug=category.slug %}">{{category.title|title}}
                        </a>
                    </li>
                    {% endif %}

                    {% endfor %}

                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">

                    {% if user.is_staff %}
                    <li class="nav-item"><a href="{% url 'post:create' %}" class="nav-link">New Post</a></li>
                    <li class="nav-item"><a href="{% url 'drafts' user.username %}" class="nav-link">My
                            Drafts</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'update_profile' %}" class="nav-link">Profile</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link">Sign Up</a></li>
                </ul>
                {% endif %}
                <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>

            </div>
        </div>
    </nav>
</header>

templates/scripts.html
{% load static %}
<!-- JavaScript files-->]



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src=" {% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>